name: "BMS Reader Simple"
version: "1.0.6" 
slug: "bms-reader-simple"
description: "Simple BMS Reader for testing"
arch:
  - armhf
  - aarch64
  - amd64
startup: application
boot: manual
stage: stable
