name: "Battery Monitor"
version: "1.0.3"
slug: "battery-monitor-new"
description: "BMS Reader for LiFePO4 batteries with MQTT integration"
arch:
  - armhf
  - aarch64
  - amd64
init: false
startup: application
boot: manual
stage: stable
homeassistant: "2023.1.0"
options:
  bms_port: "/dev/ttyUSB0"
  bms_address: 1
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  read_interval: 30
schema:
  bms_port: str
  bms_address: int(1,255)
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  read_interval: int(10,300)
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyAMA0
uart: true
